import { generateCodeReview } from './code-review'
import { createOrUpdatePRComment } from './github-comments'
import { getPRContext } from './pr-context'
import { runIOSTests, TestResult } from './ios-test-runner'

export async function runAIFlow(): Promise<void> {
  console.log('📋 Gathering PR context...')
  const prContext = await getPRContext()
  
  if (!prContext) {
    console.log('ℹ️ No PR context found, skipping AI review')
    return
  }

  console.log(`📝 Reviewing PR #${prContext.number}: ${prContext.title}`)
  
  // Post initial comment
  await createOrUpdatePRComment(
    prContext.number,
    '🤖 **AI Code Review Agent Started**\n\nAnalyzing your code changes...',
    'ai-review'
  )

  let review: any = null
  let testResult: TestResult | null = null

  try {
    // Generate code review
    console.log('🔍 Generating code review...')
    review = await generateCodeReview(prContext)
    
    console.log('✅ Code review generated successfully')
    
    // Run iOS tests
    console.log('🧪 Running iOS tests...')
    await createOrUpdatePRComment(
      prContext.number,
      `🤖 **AI Code Review Agent**\n\nCode review completed. Running iOS tests...\n\n${formatReviewSection(review)}`,
      'ai-review'
    )
    
    testResult = await runIOSTests()
    
    // Format and post the complete review with test results
    const finalComment = formatCompleteComment(review, testResult)
    await createOrUpdatePRComment(
      prContext.number,
      finalComment,
      'ai-review'
    )
    
    console.log('✅ Complete review and test results posted successfully')
    
  } catch (error) {
    console.error('❌ Error during AI flow:', error)
    
    let errorComment = '❌ **AI Code Review Failed**\n\n'
    
    if (review) {
      // If review succeeded but tests failed
      errorComment = formatCompleteComment(review, testResult || {
        success: false,
        output: 'Test execution failed',
        testsRun: 0,
        testsPassed: 0,
        testsFailed: 0,
        duration: '0s',
        failureDetails: ['Test runner encountered an error']
      })
    } else {
      // If review itself failed
      errorComment += 'Sorry, there was an error generating the code review. Please check the logs for more details.'
    }
    
    await createOrUpdatePRComment(
      prContext.number,
      errorComment,
      'ai-review'
    )
    
    throw error
  }
}

function formatReviewSection(review: any): string {
  let comment = '## 📋 Code Review\n\n'
  
  if (review.summary) {
    comment += `### Summary\n${review.summary}\n\n`
  }
  
  if (review.files && review.files.length > 0) {
    comment += '### File Analysis\n\n'
    for (const file of review.files) {
      comment += `#### 📁 \`${file.filename}\`\n`
      
      if (file.summary) {
        comment += `${file.summary}\n\n`
      }
      
      if (file.suggestions && file.suggestions.length > 0) {
        comment += '**Suggestions:**\n'
        for (const suggestion of file.suggestions) {
          comment += `- ${suggestion}\n`
        }
        comment += '\n'
      }
    }
  }
  
  if (review.overallSuggestions && review.overallSuggestions.length > 0) {
    comment += '### Overall Suggestions\n\n'
    for (const suggestion of review.overallSuggestions) {
      comment += `- ${suggestion}\n`
    }
    comment += '\n'
  }
  
  return comment
}

function formatTestSection(testResult: TestResult): string {
  let section = '## 🧪 iOS Test Results\n\n'
  
  if (testResult.success) {
    section += `✅ **Tests Passed** (${testResult.duration})\n\n`
    section += `- **Tests Run:** ${testResult.testsRun}\n`
    section += `- **Passed:** ${testResult.testsPassed}\n`
    section += `- **Failed:** ${testResult.testsFailed}\n\n`
  } else {
    section += `❌ **Tests Failed** (${testResult.duration})\n\n`
    section += `- **Tests Run:** ${testResult.testsRun}\n`
    section += `- **Passed:** ${testResult.testsPassed}\n`
    section += `- **Failed:** ${testResult.testsFailed}\n\n`
    
    if (testResult.failureDetails && testResult.failureDetails.length > 0) {
      section += '### Failure Details\n'
      for (const failure of testResult.failureDetails) {
        section += `- ${failure}\n`
      }
      section += '\n'
    }
  }
  
  return section
}

function formatCompleteComment(review: any, testResult: TestResult): string {
  let comment = '🤖 **AI Code Review Agent**\n\n'
  
  // Add review section
  comment += formatReviewSection(review)
  
  // Add test results section
  comment += formatTestSection(testResult)
  
  comment += '---\n*This review and test execution were automated by AI. Please use your judgment when considering these results.*'
  
  return comment
}

// Legacy function for backward compatibility
function formatReviewComment(review: any): string {
  return formatReviewSection(review) + '\n---\n*This review was generated by AI. Please use your judgment when considering these suggestions.*'
}
