import { generateCodeReview } from './code-review'
import { createOrUpdatePRComment } from './github-comments'
import { getPRContext } from './pr-context'

export async function runAIFlow(): Promise<void> {
  console.log('📋 Gathering PR context...')
  const prContext = await getPRContext()
  
  if (!prContext) {
    console.log('ℹ️ No PR context found, skipping AI review')
    return
  }

  console.log(`📝 Reviewing PR #${prContext.number}: ${prContext.title}`)
  
  // Post initial comment
  await createOrUpdatePRComment(
    prContext.number,
    '🤖 **AI Code Review Agent Started**\n\nAnalyzing your code changes...',
    'ai-review'
  )

  try {
    // Generate code review
    console.log('🔍 Generating code review...')
    const review = await generateCodeReview(prContext)
    
    // Format and post the review
    const reviewComment = formatReviewComment(review)
    await createOrUpdatePRComment(
      prContext.number,
      reviewComment,
      'ai-review'
    )
    
    console.log('✅ Code review posted successfully')
  } catch (error) {
    console.error('❌ Error during code review:', error)
    
    await createOrUpdatePRComment(
      prContext.number,
      '❌ **AI Code Review Failed**\n\nSorry, there was an error generating the code review. Please check the logs for more details.',
      'ai-review'
    )
    
    throw error
  }
}

function formatReviewComment(review: any): string {
  let comment = '🤖 **AI Code Review**\n\n'
  
  if (review.summary) {
    comment += `## Summary\n${review.summary}\n\n`
  }
  
  if (review.files && review.files.length > 0) {
    comment += '## File Analysis\n\n'
    for (const file of review.files) {
      comment += `### 📁 \`${file.filename}\`\n`
      
      if (file.summary) {
        comment += `${file.summary}\n\n`
      }
      
      if (file.suggestions && file.suggestions.length > 0) {
        comment += '**Suggestions:**\n'
        for (const suggestion of file.suggestions) {
          comment += `- ${suggestion}\n`
        }
        comment += '\n'
      }
    }
  }
  
  if (review.overallSuggestions && review.overallSuggestions.length > 0) {
    comment += '## Overall Suggestions\n\n'
    for (const suggestion of review.overallSuggestions) {
      comment += `- ${suggestion}\n`
    }
    comment += '\n'
  }
  
  comment += '---\n*This review was generated by AI. Please use your judgment when considering these suggestions.*'
  
  return comment
}
