import { generateCodeReview, CodeReviewResponse } from './code-review'
import { createOrUpdatePRComment } from './github-comments'
import { getPRContext } from './pr-context'
import { runIOSTests, TestResult } from './ios-test-runner'

export async function runAIFlow(): Promise<void> {
  console.log('📋 Gathering PR context...')
  const prContext = await getPRContext()
  
  if (!prContext) {
    console.log('ℹ️ No PR context found, skipping AI review')
    return
  }

  console.log(`📝 Reviewing PR #${prContext.number}: ${prContext.title}`)
  
  // Post initial comment
  await createOrUpdatePRComment(
    prContext.number,
    '🤖 **AI Code Review Agent Started**\n\nAnalyzing your code changes...',
    'ai-review'
  )

  let review: CodeReviewResponse | null = null
  // testResult kept for future use when tests are re-enabled
  // let testResult: TestResult | null = null

  try {
    // Generate code review
    console.log('🔍 Generating code review...')
    review = await generateCodeReview(prContext)

    console.log('✅ Code review generated successfully')

    // Post the complete review (tests disabled)
    const finalComment = formatReviewSection(review) + '\n---\n*This review was generated by AI. Please use your judgment when considering these suggestions.*'
    await createOrUpdatePRComment(
      prContext.number,
      finalComment,
      'ai-review'
    )

    console.log('✅ Code review posted successfully')
    
  } catch (error) {
    console.error('❌ Error during AI flow:', error)

    let errorComment = '❌ **AI Code Review Failed**\n\n'

    if (review) {
      // If review succeeded but posting failed
      errorComment = formatReviewSection(review) + '\n---\n*Note: There was an error posting this review.*'
    } else {
      // If review itself failed
      errorComment += 'Sorry, there was an error generating the code review. Please check the logs for more details.'
    }

    await createOrUpdatePRComment(
      prContext.number,
      errorComment,
      'ai-review'
    )

    throw error
  }
}

function formatReviewSection(review: CodeReviewResponse): string {
  let comment = '## 📋 Code Review\n\n'
  
  if (review.summary) {
    comment += `### Summary\n${review.summary}\n\n`
  }
  
  // Updated to use the new schema structure: fileAnalyses instead of files
  if (review.fileAnalyses && review.fileAnalyses.length > 0) {
    comment += '### File Analysis\n\n'
    for (const fileAnalysis of review.fileAnalyses) {
      comment += `#### 📁 \`${fileAnalysis.path}\`\n`
      
      if (fileAnalysis.analysis) {
        comment += `${fileAnalysis.analysis}\n\n`
      }
    }
  }
  
  if (review.overallSuggestions && review.overallSuggestions.length > 0) {
    comment += '### Overall Suggestions\n\n'
    for (const suggestion of review.overallSuggestions) {
      comment += `- ${suggestion}\n`
    }
    comment += '\n'
  }
  
  return comment
}

// Kept for future use when tests are re-enabled
function formatTestSection(testResult: TestResult): string {
  let section = '## 🧪 iOS Test Results\n\n'

  if (testResult.success) {
    section += `✅ **Tests Passed** (${testResult.duration})\n\n`
    section += `- **Tests Run:** ${testResult.testsRun}\n`
    section += `- **Passed:** ${testResult.testsPassed}\n`
    section += `- **Failed:** ${testResult.testsFailed}\n\n`
  } else {
    section += `❌ **Tests Failed** (${testResult.duration})\n\n`
    section += `- **Tests Run:** ${testResult.testsRun}\n`
    section += `- **Passed:** ${testResult.testsPassed}\n`
    section += `- **Failed:** ${testResult.testsFailed}\n\n`

    if (testResult.failureDetails && testResult.failureDetails.length > 0) {
      section += '### Failure Details\n'
      for (const failure of testResult.failureDetails) {
        section += `- ${failure}\n`
      }
      section += '\n'
    }
  }

  return section
}

// Kept for future use when tests are re-enabled
function formatCompleteComment(review: CodeReviewResponse, testResult: TestResult): string {
  let comment = '🤖 **AI Code Review Agent**\n\n'

  // Add review section
  comment += formatReviewSection(review)

  // Add test results section
  comment += formatTestSection(testResult)

  comment += '---\n*This review and test execution were automated by AI. Please use your judgment when considering these results.*'

  return comment
}

// Kept for backward compatibility
function formatReviewComment(review: CodeReviewResponse): string {
  return formatReviewSection(review) + '\n---\n*This review was generated by AI. Please use your judgment when considering these suggestions.*'
}
